language: php
php:
  - '5.6'
  - '7.0'
install:
  - composer update
  - composer install
before_script:
  - composer validate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build --debug
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --debug